CREATE FUNCTION GetDVDStockByMovieName(@Title NVARCHAR(100))
RETURNS INT
AS
BEGIN
DECLARE @DVDStock INT
SELECT  @DVDStock = DVD.Stock
FROM    DVD
JOIN    Movie
ON 	Movie.MovieID = DVD.MovieID
WHERE   Title = @Title
RETURN  @DVDStock
END;
